name: Build Image and Test with Snyk

on:
  workflow_dispatch:
  workflow_call:

  schedule:
           # ┌───────────── minute (0 - 59)
           # │ ┌───────────── hour (0 - 23)
           # │ │ ┌───────────── day of the month (1 - 31)
           # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
           # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
           # │ │ │ │ │
           # │ │ │ │ │
           # │ │ │ │ │
           # * * * * *
    - cron: '30 11 * * 5'

jobs:
  open-source-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Build Docker image
          run: docker build -t snyk-cs-goof-org/nodejs-goof .

        - name: Test Built Image with Snyk
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: snyk-cs-goof-org/nodejs-goof
            args: --file=Dockerfile
