name: Snyk Open Source Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  open-source-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Test Open Source Dependencies with Snyk
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: test

        # - name: Upload SBOM
        #   uses: actions/upload-artifact@v3
        #   with:
        #     name: sbom-cyclonedx
        #     path: sbom-cyclonedx.json
        #     retention-days: 5